
<!doctype html>
<html>
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
	<!-- Bootstrap CSS --> 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
	<meta charset="utf-8">
	<link href="style.css" rel="stylesheet">

	<link href="/python23/data/prism/prism.css" rel="stylesheet">

	<title> 
		 
		 
	</title> 
	<link rel="icon" href="data/favicon.ico" type="image/x-icon">

	<!--- mathjax latex in html---->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>
	<!--- mathjax end ---->

	</head>
	<body>
		<div id=flex>
			<nav>
				<ul>
					<li><a style="font-syze: 3em; font-weight: bold;" href="../index.html">Начало</a></li>
					<li> <a href="discassion.html">Обсуждение</a></li>
					<li><a href="error.html">Замечания</>
					<hr>

					<li><a href="code_cs50_io.html">Неделя 0</a> code.cs50.io</li>
					<li><a href="functions.html">Неделя 1</a> Переменные и фукции</li>
					<li><a href="conditionals.html">Неделя 2</a> Ветвления</li>
					<li><a href="loops.html">Неделя 3</a> Циклы</li>
					<li><a href="exceptions.html">Неделя 4</a> Исключения</li>
					<li><a href="libraries.html">Неделя 5</a> Библиотеки</a></li>
					<li><a href="unitTests.html">Неделя 6</a> Тестирование</a></li>
					<li><a href="file.html">Неделя 7</a> Файловый ввод/вывод</li>
					<li><a href="regexes.html">Неделя 8</a> Регулярные выражения</li>
					<li><a href="classes.html">Неделя 9</a> Объектно-ориентированное программирование</a></li>
					<li><a href="git.html">Неделя 10</a> Git, html, css</li>
					<li><a href="search.html">Неделя 11</a> Поиск</li>
					<li><a href="cetera.html">Неделя 12</a> Дополнения</li>
					<li><a href="knowledge.html">Неделя 13</a> Знания</li>
				</ul>
			</nav>
			<main>
				

<h1>Ошибки и исключения</h1>
Документация Python об <a href="https://digitology.tech/docs/python_3/tutorial/errors.html">ошибках и исключениях</a>.

<h2>SyntaxError, RunTimeError</h2>
Введите код и запустите.
<pre>
<code class="language-python">
print("Hello, World!)
</code>
</pre>
Вы получите сообщение о синтаксической ошибке.

<h2>Исключения, инструкция try.</h2>
Исключения помогают разделить место в программе, где 
обнаружена ошибка, от  места, где принимается решение по
дальнейшим действиям. 
Рассмотрим код:
<pre>
<code class="language-python">
x = int(input("Введите x: ")) 
print(f"x = {x}")
</code>
</pre>
Если мы введём, например, кот.
Функция int не сможет преобразовать ввод
в число, создаст исключение ValueError.
Создатель функции определил, при
каких условиях будет генерироваться исключение.
Тот, кто вызывает функцию int, может принять решение:
как обработать возникшее исключение.
Для этого он использует составную инструкцию try:
<pre>
<code class="language-python">
try: 
    x = int(input("Введите x: ")) 
    print(f"x = {x}")
except ValueError:
    print("x не целое число")
</code>
</pre>
Встретив исключение интерпретатор переходит
в блок except. Другой способ записи:
<pre>
<code class="language-python">
try: 
    x = int(input("Введите x: ")) 
except ValueError:
    print("x не целое число")
else:
    print(f"x = {x}")
</code>
</pre>

<h2>Создадим функцию для ввода целого числа</h2>
<pre>
<code class="language-python">
while True:
    try:
        x = int(input("x: "))
    except ValueError:
        print("x не целое число")
    else:
        break

print(f"x = {x}")
</code>
</pre>

Создадим функцию.
<pre>
<code class="language-python">
def main():
    x = get_int()
    print(f"x = {x}")

def get_int():
    while True:
        try:
            return int(input("x: "))
        except ValueError:
            print("x не целое число")

main()
</code>
</pre>
<h2>pass</h2>
Инструкция pass ничего не делает.
Используем эту инструкцию, для примера рассмотренного
выше:
<pre>
<code class="language-python">
def main():
    x = get_int()
    print(f"x = {x}")

def get_int():
    while True:
        try:
            return int(input("x: "))
        except ValueError:
            pass

main()
</code>
</pre>
Изменим код.
<pre>
<code class="language-python">
def main():
    x = get_int("Введите x: ")
    print(f"x = {x}")

def get_int(prompt):
    while True:
        try:
            return int(input(prompt))
        except ValueError:
            pass

main()
</code>
</pre>
Вы можете посмотреть документацию Python об инструкции 
<a href="https://digitology.tech/docs/python_3/tutorial/controlflow.html#pass">pass</a>. 

<h2>raise</h2>
raise бросает исключение, например:
<pre>
<code class="language-python">
def main():
    n = get_pos_number()
    meow(n)

def get_pos_number():
    while True:
        try:
            n = int(input("Введите положительное число: "))
            if n <= 0:
                raise ValueError
            return n
        except ValueError:
            pass

def meow(n):
    for i in range(n):
        print("мяу")

main()
</code>
</pre>


Справка по <a href="https://digitology.tech/docs/python_3/tutorial/errors.html#tut-raising">raise</a>.


			</main>
		</div>




		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
		</script> 
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
		</script> 
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
		</script>

		<script src="/python23/data/prism/prism.js"></script>
	</body>
</html>